#!/bin/bash
echo "🚀 Cafe24 서버 배포 가이드"
echo "================================"
echo ""
echo "📥 Step 1: 서버 접속"
echo "ssh 계정명@cafe24서버주소"
echo ""
echo "📦 Step 2: 프로젝트 디렉토리 이동"
echo "cd ~/webapp"
echo ""
echo "🔄 Step 3: 최신 코드 가져오기"
echo "git pull origin main"
echo ""
echo "📦 Step 4: 백엔드 패키지 업데이트 (필요시)"
echo "cd backend"
echo "source venv/bin/activate"
echo "pip install -r requirements.txt"
echo ""
echo "🔄 Step 5: PM2 재시작"
echo "cd .."
echo "pm2 restart all"
echo ""
echo "✅ Step 6: 확인"
echo "pm2 list"
echo "pm2 logs --nostream"
echo ""
echo "🌐 Step 7: 브라우저 테스트"
echo "http://도메인:3000"
echo ""
echo "================================"
echo "✅ 배포 완료!"
